# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12885O_T_aptSZSuNA67nj0ki1cENL-hW
"""

list1=["M","na","i","kh"]
list2=["y","me","s","an"]
list3=[]
for i in range(len(list1)):
  list3.append([list1[i],list2[i]])
print(list3)

list1=[10,20,[300,400,[5000,6000],500],40]
list1[2][2].append(7000)
print(list1)

candy_list= ['Jelly Belly', 'Kit Kat', 'Double Bubble', 'Milky Way', 'Three Musketeers']
no_of_items = [10, 20, 34, 74, 32]
for i in range(len(candy_list)):
   print(candy_list[i],"-",no_of_items[i])

list1=[1,2,3,4,5,6]
str(list1)
sum=0
list2=[]
for i in range(1,len(list1)+1):
  sum+=i
  list2.append(sum)
print(list2)

num1=[23,45,67,78,89,34]
num2=[34,89,55,56,39,67]
list3=[]
for i in num1:
   if i in num2:
    list3.append(i)
list3.sort()
print(list3)

list1=[2,4,6,10,1]
sum=0
n=len(list1)
for i in range(len(list1)):
  for j in range(len(list1)):
     if i>j:
      sum+=i
  print(sum)

list1=['1ac21','23fcg','456','0984','1','kls']
digit='012345689'
list2=[d for d in digit for ele in list1 if ele==d]
print(list2)

string=['CampusX is a channel', 'for data-science', 'aspirants.']
list2=[]
for ele in string:
     list2.append(ele.split())
print(list2)

string=['CampusX is a channel', 'for data-science', 'aspirants.']
list2=[word.split() for word in string]
print(list2)

list1 = [['c','a','m','p','u','x'], ['i','s'], ['b','e','s','t'], ['c','h','a','n','n','e','l']]
words=[''.join(word) for word in list1 ]
sentence=' '.join(words)

print(sentence)

list1 = ['campusxIs', 'bestFor', 'dataScientist']
new_list=[''.join([' '+char if char.isupper() else char for char in word]) for word in list1]
print(new_list)

list1=[1,2,3,4,5,1]
list2=[2,3,5,7,8]
list4=list1+list2
list3=[]
for ele in list4:
  if ele not in list3:
      list3.append(ele)
list3

